
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 28
        secondary: 11
        tertiary: 94
    emoji: ğŸ
pve_host_index: 1
pve_ip_address: 10.4.0.101
pve_mac_address: de:fe:c8:04:00:65

pve_vm_id: '101'
