
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 145
        secondary: 102
        tertiary: 145
    emoji: ğŸº
pve_host_index: 2
pve_ip_address: 10.4.0.102
pve_mac_address: de:fe:c8:04:00:66

pve_vm_id: '102'
