
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 127
        secondary: 184
        tertiary: 22
    emoji: ğŸ‹
pve_host_index: 3
pve_ip_address: 10.1.0.103
pve_mac_address: de:fe:c8:01:00:67

pve_vm_id: '103'
