description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 94
        secondary: 131
        tertiary: 59
    emoji: ğŸ‘¨â€ğŸŒ¾
pve_host_index: 3
pve_ip_address: 10.2.0.103
pve_mac_address: de:fe:c8:02:00:67

pve_vm_id: '103'
