
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 220
        secondary: 59
        tertiary: 101
    emoji: ğŸ¹
pve_host_index: 3
pve_ip_address: 10.4.0.103
pve_mac_address: de:fe:c8:04:00:67

pve_vm_id: '103'
