
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 208
        secondary: 94
        tertiary: 95
    emoji: ğŸ°
pve_host_index: 7
pve_ip_address: 10.4.0.107
pve_mac_address: de:fe:c8:04:00:6b

pve_vm_id: '107'
