
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 102
        secondary: 59
        tertiary: 102
    emoji: ğŸ
pve_host_index: 8
pve_ip_address: 10.1.0.108
pve_mac_address: de:fe:c8:01:00:6c

pve_vm_id: '108'
