
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 65
        secondary: 220
        tertiary: 22
    emoji: ğŸ—¡ï¸"
pve_host_index: 8
pve_ip_address: 10.2.0.108
pve_mac_address: de:fe:c8:02:00:6c

pve_vm_id: '108'
