
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 11
        secondary: 58
        tertiary: 145
    emoji: ğŸ¦
pve_host_index: 9
pve_ip_address: 10.1.0.109
pve_mac_address: de:fe:c8:01:00:6d

pve_vm_id: '109'
