description: |-
    Proxmox LXC Container - Kubernetes Node (Karhold)
prompt:
    colors:
        primary: 124
        secondary: 59
        tertiary: 52
    emoji: ğŸ¯
pve_host_index: 10
pve_ip_address: 10.3.0.110
pve_mac_address: de:fe:c8:03:00:6e
pve_vm_id: '110'
