description: |-
    Proxmox LXC Container - Kubernetes Master (Mistwood)
prompt:
    colors:
        primary: 37
        secondary: 28
        tertiary: 114
    emoji: ğŸ§œâ€ï¸
pve_host_index: 12
pve_ip_address: 10.1.0.112
pve_mac_address: de:fe:c8:01:00:70
pve_vm_id: '112'
