
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 28
        secondary: 220
        tertiary: 100
    emoji: ğŸ‚
pve_host_index: 14
pve_ip_address: 10.1.0.114
pve_mac_address: de:fe:c8:01:00:72

pve_vm_id: '114'
