
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 28
        secondary: 160
        tertiary: 188
    emoji: âœ‹
pve_host_index: 14
pve_ip_address: 10.2.0.114
pve_mac_address: de:fe:c8:02:00:72

pve_vm_id: '114'
