
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 174
        secondary: 59
        tertiary: 102
    emoji: ğŸ
pve_host_index: 15
pve_ip_address: 10.1.0.115
pve_mac_address: de:fe:c8:01:00:73

pve_vm_id: '115'
