
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 160
        secondary: 102
        tertiary: 160
    emoji: ğŸ‚
pve_host_index: 15
pve_ip_address: 10.3.0.115
pve_mac_address: de:fe:c8:03:00:73
pve_vm_id: '115'
