
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 124
        secondary: 222
        tertiary: 88
    emoji: ğŸ
pve_host_index: 17
pve_ip_address: 10.1.0.117
pve_mac_address: de:fe:c8:01:00:75

pve_vm_id: '117'
