
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 19
        secondary: 22
        tertiary: 131
    emoji: ğŸ‡
pve_host_index: 17
pve_ip_address: 10.2.0.117
pve_mac_address: de:fe:c8:02:00:75

pve_vm_id: '117'
