description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 160
        secondary: 94
        tertiary: 243
    emoji: ğŸ§â€â™‚ï¸
pve_host_index: 20
pve_ip_address: 10.2.0.120
pve_mac_address: de:fe:c8:02:00:78

pve_vm_id: '120'
