---

# Developer flags allow individual control over various aspects of deployment.
developer_flags:

  # Deploy dotfiles to a temporary directory instead of the user's home.
  deploy_to_temporary_directory: yes

motd_base_url: "https://raw.githubusercontent.com/ndouglas/asoiaf-noble-house-images/master/utf8/40"

hostname_emoji:
  algood: 'ğŸŒ¿'
  allyrion: 'âœ‹'
  ambrose: 'ğŸœ'
  appleton: 'ğŸŒ³'
  arlan: 'ğŸ·'
  arryn: 'ğŸ¦…'
  ashford: 'ğŸŒ'
  ball: 'â˜„'
  bar_emmon: 'ğŸŸ'
  baratheon: 'ğŸ¦Œ'
  beesbury: 'ğŸ'
  belmore: 'ğŸ””'
  bettley: 'ğŸ'
  blackbar: 'â–'
  blackfyre: 'ğŸ‰'
  blackmont: 'ğŸ¦…'
  blackwood: 'ğŸŒ³'
  blanetree: 'ğŸ'
  blount: 'ğŸ¦”'
  bolling: 'ğŸ¦Œ'
  bolton: 'ğŸ§â€â™‚'
  botley: 'ğŸŸ'
  bracken: 'ğŸ'
  brax: 'ğŸ¦„'
  bridges: 'ğŸŒ‰'
  broom: 'ğŸª–'
  buckwell: 'ğŸ¦Œ'
  burley: 'ğŸ—¡ï¸'
  butterwell: 'ã€°ï¸'
  byrch: 'ğŸª“'
  bywater: 'ğŸŸ'
  cafferen: 'ğŸ¦Œ'
  cargyll: 'ğŸ¦¢'
  caron: 'ğŸ¦œ'
  cassel: 'ğŸº'
  caswell: 'ğŸ¹'
  celtigar: 'ğŸ¦€'
  cerwyn: 'ğŸª“'
  charlton: 'ğŸŒ±'
  chelsted: 'ğŸ—¡ï¸'
  chester: 'âœ‹'
  chyttering: 'ã€½ï¸'
  clegane: 'ğŸ•'
  cockshaw: 'ğŸª¶'
  cole: 'âš«'
  condon: 'ğŸ”±'
  connington: 'ğŸ¦…'
  corbray: 'â¤ï¸'
  cordwayner: 'ğŸ‘¢'
  crakehall: 'ğŸ—'
  crane: 'ğŸ¦©'
  cressey: 'âšª'
  cuy: 'â˜€ï¸'
  dalt: 'ğŸ‹'
  darklyn: 'â–'
  darry: 'ğŸ‘¨â€ğŸŒ¾'
  dayne: 'ğŸ’«'
  doggett: 'ğŸ¦„'
  dondarrion: 'ğŸŒ©ï¸'
  donniger: 'ğŸŒ…'
  drox: 'ğŸ¹'
  drumm: 'âœ‹'
  dustin: 'ğŸª“'
  egen: 'âœ¨'
  elesham: 'ğŸŒ„'
  erenford: 'ğŸ¦©'
  estermont: 'ğŸ¢'
  estren: 'â'
  farman: 'â›µ'
  farring: 'â™'
  farwynd: 'â›µ'
  fell: 'ğŸŒƒ'
  fenn: 'ğŸŒº'
  fiddler: 'ğŸ»'
  flint: 'ğŸŒŠ'
  florent: 'ğŸ¦Š'
  foote: 'ğŸ—¡ï¸'
  fossoway: 'ğŸ'
  fowler: 'ğŸ¦…'
  frey: 'â›©ï¸'
  gardener: 'ğŸ§¤'
  garner: 'ğŸ¦‰'
  gaunt: 'ğŸ¢'
  glover: 'ğŸ§¤'
  goodbrother: 'ğŸ“¯'
  gower: 'ğŸ€'
  graceford: 'ğŸ‘©'
  grafton: 'ğŸ¯'
  grandison: 'ğŸ¦'
  graves: 'ğŸ¦…'
  greenfield: 'ğŸŸ©'
  grell: 'ğŸ¦œ'
  greyjoy: 'ğŸ¦‘'
  grimm: 'â›µ'
  harroway: 'ğŸ°'
  herston: 'ğŸ”'
  hetherspoon: 'ğŸ¥„'
  justman: 'âš–ï¸'
  karstark: 'â˜¼'
  kellington: 'ğŸ“˜'
  kettleblack: 'ğŸ¯'
  lefford: 'â˜€ï¸'
  liddle: 'ğŸŒ°'
  lightfoot: 'ğŸ‘£'
  lipps: 'ğŸ‘„'
  locke: 'ğŸ—ï¸'
  lolliston: 'ğŸ›¢ï¸'
  lothston: 'ğŸ¦‡'
  lowther: 'ğŸ¬'
  lyberr: 'ğŸ±'
  lynderly: 'ğŸ'
  mallister: 'ğŸ¦…'
  manderly: 'ğŸ§œâ€ï¸'
  manwoody: 'ğŸ’€'
  marsh: 'ğŸ¸'
  massey: 'ğŸŒ€'
  melcolm: 'âš“'
  mertyns: 'ğŸ¦‰'
  mormont: 'ğŸ»'
  mudd: 'ğŸ‘‘'
  mullendore: 'ğŸ¦‹'
  poole: 'ğŸ”µ'
  prester: 'ğŸ‚'
  qorgyle: 'ğŸ¦‚'
  rambton: 'ğŸ'
  redwyne: 'ğŸ‡'
  reed: 'ğŸŠ'
  roote: 'ğŸ'
  ryswell: 'ğŸ´'
  santagar: 'ğŸ†'
  selmy: 'ğŸŒ¾'
  shadrich: 'ğŸ'
  stackspear: 'âœ•'
  stark: 'ğŸº'
  stokeworth: 'ğŸ‘'
  swyft: 'ğŸ“'
  swygert: 'ğŸ“œ'
  targaryen: 'ğŸ‰'
  tarly: 'ğŸ¹'
  teague: 'ğŸ”±'
  tudbury: 'ğŸ¢'
  turnberry: 'ğŸ“'
  tyrell: 'ğŸµï¸'
  uller: 'ğŸ”¥'
  uthor: 'ğŸŒ'
  waxley: 'ğŸ•¯ï¸'
  webber: 'ğŸ•·ï¸'
  wensington: 'ğŸº'
  westford: 'ğŸ¶'
  wode: 'ğŸ¦”'
  wylde: 'ğŸŒ€'
  wythers: 'ğŸ¿ï¸'
  yronwood: 'â›©ï¸'

hostname_primary_colors:
  algood: 184
  allyrion: 124
  ambrose: 11
  appleton: 58
  arlan: 94
  arryn: 32
  ashford: 208
  ball: 160
  bar_emmon: 188
  baratheon: 220
  beesbury: 11
  belmore: 127
  bettley: 220
  bittersteel: 220
  blackbar: 188
  blackfyre: 124
  blackmont: 11
  blacktyde: 28
  blackwood: 166
  blanetree: 28
  bloodraven: 188
  blount: 28
  bolling: 172
  bolton: 210
  botley: 114
  bracken: 94
  brax: 188
  bridges: 20
  bronn: 65
  broom: 187
  buckler: 101
  buckwell: 19
  burley: 19
  bushy: 28
  butterwell: 28
  byrch: 28
  bywater: 188
  cafferen: 28
  cargyll: 124
  caron: 11
  cassel: 145
  caswell: 220
  celtigar: 52
  cerwyn: 59
  charlton: 28
  chelsted: 28
  chester: 28
  chyttering: 220
  city_watch: 220
  clegane: 59
  cockshaw: 173
  coldwater: 124
  cole: 202
  condon: 124
  connington: 160
  corbray: 124
  cordwayner: 28
  costayne: 185
  crakehall: 94
  crane: 39
  cressey: 19
  crowl: 124
  cuy: 184
  dalt: 127
  darklyn: 184
  darry: 94
  dayne: 140
  doggett: 28
  dondarrion: 182
  donniger: 108
  drox: 220
  drumm: 124
  dunk: 22
  dustin: 11
  edgerton: 53
  egen: 19
  elesham: 59
  erenford: 210
  estermont: 114
  estren: 28
  farman: 184
  farring: 90
  farwynd: 172
  fell: 28
  fenn: 140
  fiddler: 19
  flint: 59
  florent: 188
  foote: 130
  footly: 188
  forrester: 59
  fossoway: 220
  fowler: 19
  frey: 145
  gardener: 28
  garner: 28
  gaunt: 210
  glover: 202
  goodbrook: 220
  goodbrother: 124
  gower: 188
  graceford: 94
  grafton: 202
  grandison: 11
  graves: 28
  greenfield: 28
  grell: 19
  greyjoy: 220
  grimm: 65
  haigh: 94
  hamell: 220
  harclay: 19
  hardyng: 160
  harlaw: 145
  harlton: 28
  harroway: 208
  harte: 19
  hastwyck: 100
  hasty: 90
  hayford: 28
  herston: 124
  hersy: 174
  hetherspoon: 188
  hewett: 188
  hightower: 102
  hoare: 22
  hollard: 167
  hornwood: 172
  hunter: 94
  hutcheson: 220
  inchfield: 102
  ironsmith: 65
  jast: 11
  jordayne: 34
  justman: 19
  karstark: 102
  keath: 102
  kellington: 38
  kenning: 144
  kettleblack: 124
  kidwell: 114
  kingsguard: 102
  knott: 94
  langward: 131
  lannister: 124
  lefford: 220
  leygood: 208
  liddle: 28
  lightfoot: 94
  lipps: 18
  locke: 224
  lolliston: 94
  lonmouth: 124
  lothston: 184
  lowther: 188
  lyberr: 188
  lychester: 172
  lydden: 22
  lynderly: 28
  magnar: 188
  mallery: 90
  mallister: 188
  manderly: 37
  manning: 188
  manwoody: 223
  marbrand: 65
  marsh: 184
  martell: 208
  massey: 23
  melcolm: 80
  merryweather: 184
  mertyns: 102
  middlebury: 22
  mollen: 194
  moore: 178
  mooton: 220
  moreland: 28
  mormont: 28
  morrigen: 37
  moss: 145
  mudd: 94
  mullendore: 188
  musgood: 223
  norcross: 102
  norrey: 22
  norridge: 19
  oakheart: 28
  oldflowers: 28
  orkwood: 11
  orme: 184
  osgrey: 22
  overton: 222
  paege: 174
  parren: 125
  patrek: 19
  payne: 127
  peake: 208
  peckledon: 220
  penrose: 94
  piper: 223
  plumm: 90
  pommingham: 160
  poole: 19
  prester: 160
  pryor: 217
  pyle: 188
  qoherys: 179
  qorgyle: 124
  rambton: 124
  redding: 131
  redfort: 124
  redwyne: 19
  reed: 65
  reyne: 188
  risley: 59
  rogers: 145
  rollingford: 102
  roote: 95
  rosby: 188
  rowan: 188
  roxton: 220
  royce: 179
  ruthermont: 184
  ruttiger: 208
  ryger: 22
  rykker: 19
  ryswell: 179
  santagar: 188
  sarsfield: 28
  sarwyck: 124
  seaworth: 145
  selmy: 94
  serrett: 29
  serry: 124
  shadrich: 19
  shawney: 22
  shermer: 130
  shett: 94
  slate: 145
  sloane: 184
  slynt: 178
  smallwood: 11
  sparr: 94
  spicer: 28
  stackspear: 220
  staedmon: 124
  stark: 188
  staunton: 102
  stokeworth: 230
  stout: 94
  strong: 23
  sunderland: 22
  sunglass: 220
  swann: 230
  swyft: 11
  swygert: 127
  tallad: 224
  tallhart: 94
  tarbeck: 19
  targaryen: 124
  tarly: 28
  tarth: 209
  teague: 184
  templeton: 220
  terrick: 220
  thenn: 124
  thorne: 160
  tollett: 102
  toyne: 220
  trant: 19
  tudbury: 185
  tully: 19
  turnberry: 28
  tyrell: 220
  uffering: 95
  uller: 124
  upcliff: 37
  uthor: 188
  vaith: 208
  vance: 188
  varner: 188
  velaryon: 37
  vikary: 124
  volmark: 102
  vypren: 28
  vyrwel: 59
  wagstaff: 28
  walder: 19
  waterman: 19
  waxley: 145
  wayn: 20
  waynwood: 28
  webber: 174
  wendwater: 224
  wensington: 19
  westbrook: 28
  westerling: 186
  westford: 19
  whent: 11
  whitehill: 54
  willum: 188
  wode: 11
  woodwright: 94
  woolfield: 127
  wull: 19
  wylde: 37
  wynch: 127
  wythers: 188
  yarwyck: 160
  yelshire: 28
  yew: 124
  yronwood: 222

hostname_secondary_colors:
  algood: 19
  allyrion: 220
  ambrose: 160
  appleton: 184
  arlan: 195
  arryn: 23
  ashford: 94
  ball: 102
  bar_emmon: 19
  baratheon: 100
  beesbury: 58
  belmore: 188
  bettley: 18
  bittersteel: 160
  blackbar: 59
  blackfyre: 52
  blackmont: 167
  blacktyde: 59
  blackwood: 188
  blanetree: 11
  bloodraven: 160
  blount: 160
  bolling: 19
  bolton: 124
  botley: 188
  bracken: 220
  brax: 127
  bridges: 223
  bronn: 77
  broom: 28
  buckler: 19
  buckwell: 189
  burley: 102
  bushy: 102
  butterwell: 11
  byrch: 102
  bywater: 19
  cafferen: 71
  cargyll: 220
  caron: 59
  cassel: 102
  caswell: 58
  celtigar: 124
  cerwyn: 102
  charlton: 220
  chelsted: 188
  chester: 124
  chyttering: 94
  city_watch: 94
  clegane: 220
  cockshaw: 59
  coldwater: 19
  cole: 88
  condon: 52
  connington: 52
  corbray: 102
  cordwayner: 220
  costayne: 102
  crakehall: 102
  crane: 184
  cressey: 145
  crowl: 59
  cuy: 19
  dalt: 184
  darklyn: 160
  darry: 131
  dayne: 225
  doggett: 102
  dondarrion: 59
  donniger: 11
  drox: 59
  drumm: 188
  dunk: 130
  dustin: 59
  edgerton: 187
  egen: 184
  elesham: 210
  erenford: 220
  estermont: 22
  estren: 188
  farman: 124
  farring: 188
  farwynd: 124
  fell: 71
  fenn: 60
  fiddler: 220
  flint: 145
  florent: 17
  foote: 59
  footly: 59
  forrester: 102
  fossoway: 22
  fowler: 188
  frey: 19
  gardener: 102
  garner: 230
  gaunt: 95
  glover: 145
  goodbrook: 19
  goodbrother: 220
  gower: 184
  graceford: 230
  grafton: 184
  grandison: 100
  graves: 224
  greenfield: 188
  grell: 124
  greyjoy: 58
  grimm: 188
  haigh: 220
  hamell: 210
  harclay: 104
  hardyng: 167
  harlaw: 59
  harlton: 188
  harroway: 94
  harte: 124
  hastwyck: 229
  hasty: 139
  hayford: 184
  herston: 229
  hersy: 58
  hetherspoon: 172
  hewett: 94
  hightower: 223
  hoare: 186
  hollard: 19
  hornwood: 52
  hunter: 188
  hutcheson: 160
  inchfield: 59
  ironsmith: 220
  jast: 58
  jordayne: 185
  justman: 178
  karstark: 102
  keath: 59
  kellington: 188
  kenning: 59
  kettleblack: 59
  kidwell: 59
  kingsguard: 145
  knott: 131
  lake: 34
  langward: 175
  lannister: 220
  lefford: 32
  leygood: 94
  liddle: 131
  lightfoot: 144
  lipps: 210
  locke: 127
  lolliston: 52
  lonmouth: 11
  lothston: 188
  lowther: 37
  lyberr: 94
  lychester: 94
  lydden: 94
  lynderly: 88
  magnar: 28
  mallery: 133
  mallister: 54
  manderly: 28
  manning: 124
  manwoody: 59
  marbrand: 172
  marsh: 28
  martell: 160
  massey: 196
  melcolm: 178
  merryweather: 22
  mertyns: 145
  middlebury: 228
  mollen: 114
  moore: 58
  mooton: 160
  moreland: 94
  mormont: 114
  morrigen: 23
  moss: 28
  mudd: 220
  mullendore: 94
  musgood: 19
  norcross: 59
  norrey: 11
  norridge: 173
  oakheart: 220
  oldflowers: 160
  orkwood: 22
  orme: 188
  osgrey: 184
  overton: 101
  paege: 59
  parren: 220
  patrek: 188
  payne: 220
  peake: 94
  peckledon: 90
  penrose: 188
  piper: 19
  plumm: 220
  pommingham: 52
  poole: 102
  prester: 102
  pryor: 11
  pyle: 59
  qoherys: 124
  qorgyle: 167
  rambton: 222
  redding: 220
  redfort: 52
  redwyne: 22
  reed: 59
  reyne: 124
  risley: 124
  rogers: 59
  rollingford: 62
  roote: 28
  rosby: 160
  rowan: 178
  roxton: 32
  royce: 94
  ruthermont: 58
  ruttiger: 58
  ryger: 188
  rykker: 102
  ryswell: 160
  santagar: 19
  sarsfield: 108
  sarwyck: 188
  seaworth: 59
  selmy: 11
  serrett: 187
  serry: 52
  shadrich: 94
  shawney: 160
  shermer: 20
  shett: 184
  slate: 59
  sloane: 54
  slynt: 58
  smallwood: 52
  sparr: 19
  spicer: 187
  stackspear: 188
  staedmon: 52
  stark: 59
  staunton: 145
  stokeworth: 28
  stout: 220
  strong: 160
  sunderland: 19
  sunglass: 186
  swann: 144
  swyft: 18
  swygert: 95
  tallad: 19
  tallhart: 22
  tarbeck: 188
  targaryen: 188
  tarly: 124
  tarth: 19
  teague: 94
  templeton: 94
  terrick: 127
  thenn: 179
  thorne: 188
  tollett: 59
  toyne: 59
  trant: 62
  tudbury: 28
  tully: 124
  turnberry: 124
  tyrell: 28
  uffering: 22
  uller: 11
  upcliff: 23
  uthor: 28
  vaith: 11
  varner: 59
  velaryon: 188
  vikary: 220
  volmark: 145
  vypren: 108
  vyrwel: 167
  wagstaff: 11
  walder: 102
  waterman: 95
  waxley: 102
  wayn: 146
  waynwood: 71
  webber: 59
  wendwater: 28
  wensington: 220
  westbrook: 11
  westerling: 95
  westford: 188
  whent: 100
  whitehill: 103
  willum: 102
  wode: 188
  woodwright: 124
  woolfield: 102
  wull: 102
  wylde: 220
  wynch: 196
  wythers: 124
  yarwyck: 179
  yelshire: 184
  yew: 184
  yronwood: 101

hostname_tertiary_colors:
  algood: 94
  allyrion: 52
  ambrose: 172
  appleton: 102
  arlan: 108
  arryn: 117
  ashford: 222
  ball: 160
  bar_emmon: 102
  baratheon: 94
  beesbury: 100
  belmore: 59
  bettley: 94
  bittersteel: 94
  blackbar: 102
  blackfyre: 224
  blackmont: 100
  blacktyde: 28
  blackwood: 102
  blanetree: 94
  bloodraven: 102
  blount: 59
  bolling: 101
  bolton: 52
  botley: 59
  bracken: 166
  brax: 102
  bridges: 143
  bronn: 188
  broom: 70
  buckler: 143
  buckwell: 220
  burley: 60
  bushy: 108
  butterwell: 101
  byrch: 71
  bywater: 62
  cafferen: 102
  cargyll: 58
  caron: 100
  cassel: 145
  caswell: 102
  celtigar: 102
  cerwyn: 59
  charlton: 71
  chelsted: 59
  chester: 220
  chyttering: 102
  city_watch: 100
  clegane: 100
  cockshaw: 102
  coldwater: 104
  cole: 130
  condon: 102
  connington: 145
  corbray: 124
  cordwayner: 100
  costayne: 136
  crakehall: 160
  crane: 30
  cressey: 160
  crowl: 52
  cuy: 100
  dalt: 22
  darklyn: 58
  darry: 59
  dayne: 59
  doggett: 145
  dondarrion: 102
  donniger: 160
  drox: 101
  drumm: 52
  dunk: 178
  dustin: 130
  edgerton: 166
  egen: 145
  elesham: 95
  erenford: 95
  estermont: 59
  estren: 124
  farman: 19
  farring: 145
  farwynd: 59
  fell: 102
  fenn: 59
  fiddler: 100
  flint: 59
  florent: 172
  foote: 102
  footly: 102
  forrester: 59
  fossoway: 160
  fowler: 59
  frey: 59
  gardener: 108
  garner: 130
  gaunt: 59
  glover: 102
  goodbrook: 94
  goodbrother: 167
  gower: 59
  graceford: 145
  grafton: 100
  grandison: 188
  graves: 108
  greenfield: 108
  grell: 103
  greyjoy: 59
  grimm: 52
  haigh: 137
  hamell: 100
  harclay: 19
  hardyng: 174
  harlaw: 102
  harlton: 102
  harroway: 95
  harte: 61
  hastwyck: 186
  hasty: 176
  hayford: 106
  herston: 58
  hersy: 95
  hetherspoon: 94
  hewett: 19
  hightower: 145
  hoare: 32
  hollard: 215
  hornwood: 215
  hunter: 145
  hutcheson: 94
  inchfield: 102
  ironsmith: 22
  jast: 145
  jordayne: 70
  justman: 103
  karstark: 102
  keath: 178
  kellington: 178
  kettleblack: 52
  kidwell: 114
  kingsguard: 102
  knott: 102
  lake: 58
  langward: 174
  lannister: 167
  lefford: 58
  leygood: 130
  liddle: 108
  lightfoot: 94
  lipps: 61
  locke: 94
  lolliston: 137
  lonmouth: 100
  lothston: 59
  lowther: 80
  lyberr: 102
  lychester: 215
  lydden: 102
  lynderly: 59
  magnar: 102
  mallery: 139
  mallister: 102
  manderly: 114
  manning: 59
  manwoody: 102
  marbrand: 52
  marsh: 94
  martell: 11
  massey: 102
  melcolm: 53
  merryweather: 89
  mertyns: 102
  middlebury: 71
  mollen: 59
  moore: 186
  mooton: 102
  moreland: 58
  mormont: 59
  morrigen: 30
  moss: 208
  mudd: 22
  mullendore: 172
  musgood: 22
  norcross: 102
  norrey: 100
  norridge: 60
  oakheart: 100
  oldflowers: 188
  orkwood: 100
  orme: 59
  osgrey: 102
  overton: 102
  paege: 102
  parren: 137
  patrek: 60
  payne: 225
  peake: 59
  peckledon: 94
  penrose: 145
  piper: 17
  plumm: 94
  pommingham: 138
  poole: 19
  prester: 160
  pryor: 95
  pyle: 102
  qoherys: 101
  qorgyle: 160
  rambton: 88
  redding: 188
  redfort: 174
  redwyne: 131
  reed: 108
  reyne: 52
  risley: 184
  rogers: 102
  rollingford: 18
  roote: 40
  rosby: 102
  rowan: 101
  roxton: 59
  royce: 58
  ruthermont: 100
  ruttiger: 94
  ryger: 102
  rykker: 145
  ryswell: 138
  santagar: 184
  sarsfield: 28
  sarwyck: 52
  seaworth: 145
  selmy: 137
  serrett: 107
  serry: 174
  shadrich: 188
  shawney: 20
  shermer: 53
  slate: 102
  sloane: 189
  slynt: 59
  smallwood: 94
  sparr: 95
  spicer: 108
  stackspear: 144
  staedmon: 59
  stark: 102
  staunton: 102
  stokeworth: 71
  stout: 95
  strong: 28
  sunderland: 28
  sunglass: 102
  swann: 102
  swyft: 100
  swygert: 176
  tallad: 104
  tallhart: 71
  tarbeck: 104
  targaryen: 102
  tarly: 52
  tarth: 189
  teague: 100
  templeton: 100
  terrick: 94
  thenn: 102
  thorne: 59
  tollett: 102
  toyne: 101
  trant: 20
  tudbury: 106
  tully: 188
  turnberry: 172
  tyrell: 71
  uffering: 145
  uller: 136
  upcliff: 30
  uthor: 71
  vaith: 101
  varner: 102
  velaryon: 23
  vikary: 52
  volmark: 102
  vypren: 102
  vyrwel: 95
  wagstaff: 70
  walder: 60
  waterman: 137
  waxley: 160
  wayn: 20
  waynwood: 22
  webber: 102
  wendwater: 52
  wensington: 100
  westbrook: 106
  westerling: 186
  westford: 17
  whent: 102
  whitehill: 54
  willum: 188
  wode: 100
  woodwright: 167
  woolfield: 127
  wull: 59
  wylde: 94
  wynch: 167
  wythers: 102
  yarwyck: 102
  yelshire: 58
  yew: 102
  yronwood: 95
